-- 학생 테이블
CREATE TABLE STUDENT (
  UID             VARCHAR2(50) PRIMARY KEY,
  NAME            VARCHAR(50),
  DEPARTMENT_CODE VARCHAR(50)
);

-- 학과 테이블
CREATE TABLE DEPARTMENT (
  CODE        VARCHAR2(50) PRIMARY KEY,
  NAME        VARCHAR2(100)
);

-- 과목
CREATE TABLE SUBJECT (
  CODE            VARCHAR2(50) PRIMARY KEY,
  NAME            VARCHAR2(50),
  GRADE           TINYINT(1)
);

-- 과목 시간
CREATE TABLE SUBJECT_TIME (
  SEQ          NUMBER PRIMARY KEY   AUTO_INCREMENT,
  SUBJECT_CODE VARCHAR2(50),
  DAY_OF_WEEK  CHAR(1),
  START_TIME   TIME,
  END_TIME     TIME
);

